sudo: false

language: node_js

install:
  - npm install -g elm@0.18.0 elm-test@0.18.12 elm-format
  - travis_retry elm-package install -y
  - cd tests
  - travis_retry elm-package install -y
  - cd ..

script:
  - elm-format --validate src tests
  - elm-make --yes
  - elm-test